theme: jekyll-theme-cayman
title: ML Corrective Deformer for Maya
description: Pose-Based Corrective Blendshape Prediction Using Machine Learning
show_downloads: true
google_analytics: 
author: Mayj Amilano
